### ISSUE TITLE
如何实现 scrollto 的效果

### ISSUE THREAD

**Issue by WuYunlong** [custom-lib/custom-vue-scrollbar#1]
如何实现 scrollto 的效果

**Comment by SSSensational** [comment]
抱歉这么晚才看到。需要更新一下版本至0.0.7，我在ref中导出了scrollEl。具体可以看README里的基础用法，demo中也更新在了[基础用法](https://github.com/custom-lib/custom-vue-scrollbar/blob/main/website/examples/BasicUsage.vue)那一栏。
